// Generated by CoffeeScript 1.6.2
(function() {
  describe("ruc jquery validator plugin", function() {
    return it("should have already loaded jQuery 1.9.1 in $", function() {
      return expect($.fn.jquery).toEqual("1.9.1");
    });
  });

}).call(this);
