// Generated by CoffeeScript 1.6.2
(function() {
  describe("load dependences", function() {
    it("should have already loaded jQuery 1.9.1 in $", function() {
      return expect($.fn.jquery).toEqual("1.9.1");
    });
    return it("should have loaded validarCedulaEC in $.fn", function() {
      return expect($.fn.validarCedulaEC).toBeDefined();
    });
  });

  describe("ruc jquery validator plugin", function() {
    return describe("DOM behavior", function() {
      var $input;

      $input = null;
      beforeEach(function() {
        return $input = $("input", {
          type: "text"
        });
      });
      return it("should create an input node, fill it with a valid RUC number and apply the method");
    });
  });

}).call(this);
