// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  (function($) {
    var RucValidatorEc;

    RucValidatorEc = (function() {
      function RucValidatorEc($node, options) {
        this.$node = $node;
        this.options = options;
        this.validateContent = __bind(this.validateContent, this);
        this.$node.on("change", this.validateContent);
      }

      RucValidatorEc.prototype.validateCI = function(ci) {};

      RucValidatorEc.prototype.validateContent = function() {
        var length, value;

        console.log(this.$node);
        value = this.$node.val().toString();
        length = value.length;
        if (length === 10 || length === 13) {
          return console.log("length ok.");
        } else {
          return console.log("length not ok.");
        }
      };

      return RucValidatorEc;

    })();
    $.fn.validarCedulaEC = function(options) {
      options = $.extend({}, $.fn.validarCedulaEC.defaults, options);
      this.each(function() {
        return new RucValidatorEc($(this), options);
      });
      return this;
    };
    return $.fn.validarCedulaEC.defaults = {
      onValid: function() {
        return null;
      },
      onInvalid: function() {
        return null;
      }
    };
  })(jQuery);

}).call(this);
